# This workflow will install Python dependencies, run py2exe

name: Build .exe file

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.9
      uses: actions/setup-python@v3
      with:
        python-version: "3.9"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run py2exe
      run: |
        python setup.py
    - name: Upload as artifact
      uses: actions/upload-artifact@v3
      with:
        name: py2exe
        path: ./dist
